pr:
  - master

pool: 
  vmImage: 'windows-latest'

variables:
 - group: 'Secrets'
 - name: solution
   value: '**/*.sln'
 - name: buildPlatform
   value: 'Any CPU'
 - name: buildConfiguration
   value: 'Release'

steps:

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishPipelineArtifact@1
  displayName: 'Publish DACPAC as artifact for current run'
  inputs:
    targetPath: $(Build.SourcesDirectory)
    artifactName: 'sqlproj_artifacts_$(System.JobAttempt)'
  condition: always()

- task: SqlAzureDacpacDeployment@1
  displayName: 'Deploy Azure SQL DB'
  inputs:
    azureSubscription: '$(azureSubscription)'
    ServerName: '$(azureSqlServerName)'
    DatabaseName: '$(azureSqlDBName)'
    SqlUsername: '$(azureSqlUser)'
    SqlPassword: '$(azureSqlPassword)'
    DacpacFile: '$(System.DefaultWorkingDirectory)/WideWorldImporters/bin/Release/WideWorldImporters.dacpac'
    PublishProfile: '$(System.DefaultWorkingDirectory)/WideWorldImporters/WideWorldImporters.publish.xml'
    DeleteFirewallRule: false